# The URL the site will be built for
base_url = "https://glib.org.mx"

default_language = "es"

taxonomies = [ {name = "tema"}, {name = "autor"} ]

[slugify]
paths = "safe"

[extra]
# Put all your custom variables here
