name: publicar

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publicar:
    runs-on: ubuntu-latest
    
    environment:
      name: despliegue
      
    env:
      ZOLA_VERSION: v0.18.0
      
    steps:
      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client rsync

      - name: Actualizar sistema a Español
        run: |
          sudo locale-gen es_MX.UTF-8
          sudo update-locale

      - name: Extraer repositorio
        uses: actions/checkout@v4

      - name: Descargar Zola
        run: |
          wget "https://github.com/getzola/zola/releases/download/${ZOLA_VERSION}/zola-${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz"

      - name: Instalar Zola
        run: |
          tar vxzf ./zola-${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz

      - name: Construir sitio web
        run: |
          LANG=es_MX.UTF-8 ./zola build
          find public

      - name: Instalar llave SSH
        env:
          KEY: ${{ secrets.SSH_ID }}
        run: |
          echo "$KEY" > deploy_key''
          chmod 600 ./deploy_key

      - name: Desplegar en servidor
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PORT: ${{ secrets.PORT }}
        run: |
          rsync -P -rvzc --delete \
            -e 'ssh -i ./deploy_key -p 6789 -o StrictHostKeyChecking=no' \
            public/ "$USER"@"$HOST":~/public_html
          
